-- ============================================================================
-- DEPRECATED / NOT USED BY THE LIVE SITE.
-- This is the SQLite schema for the old local Flask prototype (app.py). The
-- deployed website uses Supabase. The SOURCE OF TRUTH is: supabase_schema.sql
-- This file has drifted (no inventory table, no profile/bike/queue columns the
-- live app uses) and is kept only for reference.
-- ============================================================================
-- MicroMobility Corniche Circuit - Database Schema
-- Engine: SQLite (file: micromobility.db)
-- Generated by: app.py on first run (CREATE TABLE IF NOT EXISTS)

-- ── CUSTOMERS ──────────────────────────────────────────────────────────────
-- One row per registered account. Customers sign up via the web app.
-- Login uses email OR phone + password_hash (djb2 hash computed client-side).

CREATE TABLE IF NOT EXISTS customers (
    id            TEXT PRIMARY KEY,           -- client-generated uid
    name          TEXT NOT NULL,              -- full name
    email         TEXT,                       -- optional if phone provided
    phone         TEXT,                       -- full international format, e.g. +966512345678
    password_hash TEXT NOT NULL,              -- djb2 hash of the password
    created_at    INTEGER NOT NULL,           -- Unix ms timestamp
    height        INTEGER                     -- rider height in cm (100–250); drives automatic bike size selection
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_email ON customers(email) WHERE email != '';
CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_phone ON customers(phone) WHERE phone != '';

-- ── BIKES ──────────────────────────────────────────────────────────────────
-- Fleet inventory. Staff manage this via the Bikes tab.

CREATE TABLE IF NOT EXISTS bikes (
    id     TEXT PRIMARY KEY,           -- client-generated uid
    name   TEXT NOT NULL,              -- e.g. "Spectra One"
    size   TEXT NOT NULL,              -- XS | S | M | L
    type   TEXT NOT NULL,              -- Road | Hybrid | Mountain | Gravel
    colors TEXT NOT NULL,              -- JSON array of hex strings, e.g. ["#6ee89a","#4aa8f8"]
    status TEXT NOT NULL DEFAULT 'available'  -- available | in-use | maintenance
);

-- ── QUEUE ENTRIES ──────────────────────────────────────────────────────────
-- One row per booking. Both online registrations and staff walk-ins.
-- A session is identified by session_id (ISO date string, e.g. "2026-06-08").
-- Sessions run Sundays and Tuesdays, max 12 spots each.

CREATE TABLE IF NOT EXISTS queue_entries (
    id               TEXT PRIMARY KEY,                  -- client-generated uid
    name             TEXT NOT NULL,                     -- rider full name
    email            TEXT,                              -- rider email (may be empty for walk-ins)
    phone            TEXT,                              -- rider phone in international format
    size             TEXT NOT NULL,                     -- XS | S | M | L (auto from height)
    type_preference  TEXT NOT NULL,                     -- Road | Hybrid | Mountain | Gravel | Any
    paid             INTEGER NOT NULL DEFAULT 0,        -- 0 = pending, 1 = paid
    price            REAL    NOT NULL DEFAULT 30,       -- SAR amount for this booking
    assigned_bike_id TEXT    REFERENCES bikes(id),      -- null until staff assigns
    session_id       TEXT    NOT NULL,                  -- ISO date string of the session
    session_day      TEXT    NOT NULL,                  -- "Sunday" | "Tuesday"
    session_date     TEXT    NOT NULL,                  -- same as session_id (display copy)
    queue_num        INTEGER NOT NULL,                  -- position in session queue, starts at 1
    status           TEXT    NOT NULL DEFAULT 'waiting',-- waiting | active | done | noshow
    registered_at    INTEGER NOT NULL,                  -- Unix ms timestamp
    walk_in          INTEGER NOT NULL DEFAULT 0,        -- 0 = online, 1 = walk-in
    customer_id      TEXT    REFERENCES customers(id),  -- null for walk-ins or unregistered

    FOREIGN KEY (assigned_bike_id) REFERENCES bikes(id),
    FOREIGN KEY (customer_id)      REFERENCES customers(id)
);

CREATE INDEX IF NOT EXISTS idx_queue_session  ON queue_entries(session_id);
CREATE INDEX IF NOT EXISTS idx_queue_customer ON queue_entries(customer_id);
CREATE INDEX IF NOT EXISTS idx_queue_status   ON queue_entries(status);
CREATE INDEX IF NOT EXISTS idx_queue_session_date ON queue_entries(session_date); -- speeds the recent-window load
CREATE INDEX IF NOT EXISTS idx_cashier_session ON cashier_sales(session_id);

-- ── USEFUL QUERIES ─────────────────────────────────────────────────────────

-- Spots remaining in a session:
-- SELECT 12 - COUNT(*) FROM queue_entries
--   WHERE session_id = '2026-06-08' AND status != 'noshow';

-- Next queue number for a session:
-- SELECT COALESCE(MAX(queue_num), 0) + 1 FROM queue_entries WHERE session_id = '2026-06-08';

-- Customer ride history:
-- SELECT q.*, b.name AS bike_name FROM queue_entries q
--   LEFT JOIN bikes b ON b.id = q.assigned_bike_id
--   WHERE q.customer_id = '<id>' ORDER BY q.registered_at DESC;

-- Customer totals:
-- SELECT
--   COUNT(*) FILTER (WHERE status != 'noshow') AS total_bookings,
--   COUNT(*) FILTER (WHERE status = 'done')    AS completed,
--   SUM(price) FILTER (WHERE paid = 1)         AS total_paid_sar,
--   SUM(price) FILTER (WHERE paid = 0 AND status IN ('waiting','active','done')) AS pending_sar
-- FROM queue_entries WHERE customer_id = '<id>';

-- Revenue summary:
-- SELECT SUM(price) FROM queue_entries WHERE paid = 1;

-- All-time leaderboard (most rides):
-- SELECT c.name, COUNT(q.id) AS rides, SUM(q.price) FILTER (WHERE q.paid=1) AS paid_sar
--   FROM customers c JOIN queue_entries q ON q.customer_id = c.id
--   WHERE q.status = 'done'
--   GROUP BY c.id ORDER BY rides DESC;
