-- ─────────────────────────────────────────────────────────────────────────────
-- Closing the last PII hole on queue_entries, in two stages.
--
-- `public read using(true)` was the one place the anon key shipped in the bundle
-- could read ~2,700 riders' names, emails and phone numbers. It was not left open
-- by oversight: dropping it broke booking live in August, because the form did
-- `.insert(...).select()` and RETURNING applies SELECT policies to the new row.
--
-- ── STAGE 1 — APPLIED 2026-08-24, and verified ───────────────────────────────
-- Reads had already moved: customers get the no-PII queue_public view plus their
-- own rows through the token-checked my_bookings() RPC, and staff read the table
-- under is_staff(). Nothing else needs SELECT — supabase-js v2 does not return
-- rows from an insert unless .select() is chained, so even a stale cached client
-- does not depend on it.
--
--   drop policy if exists "public read" on public.queue_entries;
--
-- Verified immediately after, impersonating the anon role:
--   queue_entries → 0 rows        (was ~2,743, with full PII)
--   queue_public  → 2,743 rows    (no PII; the app keeps working)
--
-- ── STAGE 2 — NOT YET APPLIED ────────────────────────────────────────────────
-- The INSERT policy is deliberately still open. It is not a PII leak: price, paid
-- and status are all enforced by triggers, and customer_create_booking() is what
-- new clients use. It matters for one case only — a booking made OFFLINE on a
-- client older than 2026-08-24, whose outbox still flushes by inserting directly.
-- Dropping it before those clients have rolled over would refuse that flush
-- forever: the rider turns up expecting a bike, the roster has never heard of
-- them, and nothing on any screen says so.
--
-- Apply this once the client that flushes through the RPC has been live for a few
-- days (the service worker serves navigations stale-while-revalidate, so a device
-- picks it up on its next load):
--
--   drop policy if exists "public insert booking" on public.queue_entries;
--
-- Then make one real booking as a signed-out visitor, online, to confirm.
--
-- ── Rollback, if booking breaks ──────────────────────────────────────────────
-- create policy "public read" on public.queue_entries for select using (true);
-- create policy "public insert booking" on public.queue_entries for insert with check (true);
-- ─────────────────────────────────────────────────────────────────────────────

-- Stage 1, as applied:
drop policy if exists "public read" on public.queue_entries;
